### ISSUE TITLE
Draft v0.10.1 Umbrella

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1158]
Current status of the v0.10.1 release, which will include some high impact fixes/improvements such as https://github.com/facebook/draft-js/pull/1155 and https://github.com/facebook/draft-js/pull/796

- [x] Fix https://github.com/facebook/draft-js/issues/1157
- [x] [Manual test plan](https://github.com/facebook/draft-js/wiki/Manual-Testing) on master in all browsers
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [x] IE/Edge
  - [ ] Bonus: Android Chrome
  - [ ] Bonus: iOS Chrome
- [x] Fix any failures/errors on master found in manual testing, or at least open issues
- [x] Internal sync with Facebook
- [x] Internal manual testing across browsers
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [x] IE/Edge
  - [x] Bonus: Android Chrome
  - [ ] Bonus: iOS Chrome
- [x] Fix/document any issues flagged during this testing
- [x] Release v0.10.1

**Comment by flarnie** [comment]
Currently working through the manual test plan in IE/Edge. Found one bug so far - https://github.com/facebook/draft-js/issues/1164

I'm thinking that it should not block releasing v0.10.1, especially since it is present in v0.10.0 also.

**Comment by flarnie** [comment]
I did find some bugs on IE/Edge while testing, and saw that currently open bugs are still there. Still planning to release master but ideally we will continue working on fixing these for future releases.
https://github.com/facebook/draft-js/issues?q=is%3Aopen+is%3Aissue+label%3Aie

**Comment by flarnie** [comment]
Would love it if someone ran through the manual test plan with the master branch on Firefox or Safari.

**Comment by MadebyAe** [comment]
@flarnie I can test Safari

**Comment by flarnie** [comment]
That would be great @MadebyAe - please open issues for any bugs you find, and comment here on the status. Mainly looking for anything serious enough to block the release. Currently known Safari bugs should be in the issues under the 'Safari' label. I don't see any right now though - https://github.com/facebook/draft-js/issues?q=is%3Aopen+is%3Aissue+label%3Asafari
