### ISSUE TITLE
Move to GitHub-first sync process

### ISSUE THREAD

**Issue by zpao** [facebook/draft-js#500]
After talking with @hellendag, we've decided that the best thing to help Draft continue to grow and be healthy is to move to a GitHub-first model. This should make it much easier to accept pull requests more freely and sync into Facebook in batches. There are still a few things to figure out process-wise but we can start from the tooling side.
## External
- [x] Update to latest build process - @zpao (#389)
- [ ] Ensure linting and tests are dependable, match FB expectations, CI fails appropriately - @zpao
- [x] Set up issue & PR templates ([docs](https://help.github.com/articles/creating-an-issue-template-for-your-repository/), [React's](https://github.com/facebook/react/pull/6597)) - @hellendag
- [x] Document testing guidelines - @hellendag
- [x] Document manual test plan - @hellendag
## Internal
- [x] Write sync script (can crib from React's)

There are surely some other things, we can add as we go.

**Comment by mitermayer** [comment]
wohooooo!! amazing!

**Comment by mitermayer** [comment]
Let me know if there is anything I can do to help

**Comment by spicyj** [comment]
Is this done?

**Comment by zpao** [comment]
Effectively. shipit is off. I'll still make linting stricter.

**Comment by mitermayer** [comment]
is this done ? can we close this ?

**Comment by flarnie** [comment]
Not only was this completed, but I am now moving us back to FB first. See https://github.com/facebook/draft-js/issues/1244
